"""X5. Measure the perception stack on real pixels, against truth that is still exact.

Footage has no ground truth, and hand-labelling a few clips would give a suite too small to notice
a regression in. So the truth is *constructed around* the footage: real clips are assembled into a
Cadence comp, which fixes the things being scored — where each cut falls, and where a moving inset
sits in every frame — to the frame and to the pixel, while every pixel the producers see comes from
a camera. The perception stack is then asked to recover from the render what the comp already knows.

Two scores, both the ones the benchmarks report:

  * **cut localization**, as an off-by-N-frames histogram. tIoU on shots hides the failure that
    matters — a cut found one frame late is nearly perfect by overlap and still wrong in an edit.
  * **inset localization**, as per-frame IoU and as temporal IoU of the interval the entity is
    claimed visible against the interval it is actually on screen.

The seeder is not told where the inset is; it has to find it the way it would on any clip. A run
that never seeds it scores zero recall, which is the honest result and the one worth fixing.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np

from . import ROOT
from .facts import parse_log

W, H = 1280, 720
FPS = 30
INSET_W, INSET_H = 384, 216
SEG = 3.0                      # seconds of each source clip per shot
NEAR_FRAMES = (0, 1, 2, 3, 5)


# ----------------------------------------------------------------------------- build

COMP = '''-- Generated by cadence_vision.clipeval: real footage, exact cut times, exact inset geometry.
-- The pixels come from a camera; the truth comes from this scene graph.
local e = require("ellua")

return e.comp {{
  width = {W}, height = {H}, duration = {dur}, fps = {fps},
  background = "#000000",

  scene = function(s)
{plates}
    local inset = s:video {{
      src = "{inset_src}", from = {inset_from}, duration = {inset_dur}, media_start = 0,
      w = {iw}, h = {ih}, x = {x0}, y = {y0}, rx = 8,
    }}
    s:script(function(t)
      t:wait({inset_from})
      t:tween(inset, {travel}, {{ x = {x1} }}, "linear")
    end)
  end,
}}
'''

PLATE = ('    s:video {{ src = "{src}", from = {t0}, duration = {d}, media_start = {ms}, '
         'w = {W}, h = {H}, x = 0, y = 0 }}')


def build(clips: list[Path], out: Path, seg: float = SEG) -> dict:
    """Write a comp that cuts between `clips` and floats one of them as a travelling inset."""
    clips = [c for c in clips if c.exists()]
    if len(clips) < 2:
        raise SystemExit("clipeval: need at least two source clips")
    dur = round(len(clips) * seg, 3)
    plates, cuts = [], []
    for i, c in enumerate(clips):
        t0 = round(i * seg, 3)
        # Each plate takes a different window of its source, so passing the same clip twice gives
        # two shots of the same subject at different moments rather than the identical frames —
        # which is what makes cross-shot identity a real question and not a pixel comparison.
        plates.append(PLATE.format(src=_rel(c), t0=t0, d=seg, ms=round(0.5 + i * seg, 3), W=W, H=H))
        if i:
            cuts.append(t0)
    # The inset spans the middle cut, so recovering it also tests that propagation is not fooled by
    # a hard cut in the plate behind it.
    inset_from = round(seg * 0.6, 3)
    inset_dur = round(min(seg * 1.8, dur - inset_from), 3)
    x0, x1 = 80, W - INSET_W - 80
    y0 = H - INSET_H - 80
    comp = COMP.format(W=W, H=H, dur=dur, fps=FPS, plates="\n".join(plates),
                       inset_src=_rel(clips[-1]), inset_from=inset_from, inset_dur=inset_dur,
                       iw=INSET_W, ih=INSET_H, x0=x0, y0=y0, x1=x1,
                       travel=round(inset_dur * 0.9, 3))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(comp)

    n = int(round(inset_dur * 0.9 * FPS))
    track = {}
    for f in range(int(round(inset_dur * FPS)) + 1):
        t = round(inset_from + f / FPS, 4)
        x = x0 + (x1 - x0) * min(1.0, f / max(n, 1))
        track[f"{t:.4f}"] = [x / W, y0 / H, (x + INSET_W) / W, (y0 + INSET_H) / H]
    truth = {"comp": str(out), "duration": dur, "fps": FPS, "cuts": cuts,
             "sources": [_rel(c) for c in clips],
             "inset": {"t0": inset_from, "t1": round(inset_from + inset_dur, 3), "box_at": track}}
    out.with_suffix(".truth.json").write_text(json.dumps(truth, indent=1))
    return truth


def _rel(p: Path) -> str:
    try:
        return str(p.resolve().relative_to(ROOT))
    except ValueError:
        return str(p.resolve())


# ----------------------------------------------------------------------------- score

def score_cuts(truth: list[float], got: list[float], fps: int = FPS) -> dict:
    """Off-by-N frames, not overlap. A cut one frame late reads as correct under tIoU and is not."""
    got = sorted(got)
    used, errs = set(), []
    for t in truth:
        cand = [(abs(g - t), i) for i, g in enumerate(got) if i not in used]
        if not cand:
            errs.append(None)
            continue
        d, i = min(cand)
        if d > 0.5:                   # nothing within half a second is a miss, not a sloppy hit
            errs.append(None)
            continue
        used.add(i)
        errs.append(round(d * fps, 2))
    hit = [e for e in errs if e is not None]
    return {"truth": len(truth), "found": len(got), "matched": len(hit),
            "missed": sum(1 for e in errs if e is None), "false_positives": len(got) - len(used),
            "within": {f"<={n}f": sum(1 for e in hit if e <= n + 1e-6) for n in NEAR_FRAMES},
            "median_frames": round(float(np.median(hit)), 2) if hit else None,
            "max_frames": round(max(hit), 2) if hit else None}


def _iou(a, b) -> float:
    iw = max(0.0, min(a[2], b[2]) - max(a[0], b[0]))
    ih = max(0.0, min(a[3], b[3]) - max(a[1], b[1]))
    inter = iw * ih
    u = (a[2] - a[0]) * (a[3] - a[1]) + (b[2] - b[0]) * (b[3] - b[1]) - inter
    return inter / u if u > 0 else 0.0


def score_inset(truth: dict, tracks: list[dict]) -> dict:
    """Best-matching track against the inset: spatial IoU per sample, plus temporal IoU.

    A track that never once reaches half-overlap with the inset is not the inset, whatever its
    temporal IoU says. Two entities can share an interval by coincidence — a person visible for the
    same seconds the inset is on screen scores a high tIoU while sitting somewhere else entirely —
    and reporting that number next to a spatial IoU of 0.2 reads as a localization that did not
    happen. So the match is marked `matched: False` and the temporal figure withheld. Silence is
    the right output when the thing being scored was not found; that applies to the harness too.
    """
    box_at = {float(k): v for k, v in truth["box_at"].items()}
    tt = np.array(sorted(box_at))
    best = None
    for tr in tracks:
        ious, span = [], []
        for o in tr["obs"]:
            t = o[0]
            k = float(tt[int(np.argmin(np.abs(tt - t)))])
            if abs(k - t) > 0.06:
                continue
            ious.append(_iou(o[1], box_at[k]))
            span.append(t)
        if not ious:
            continue
        m = float(np.mean(ious))
        if best is None or m > best["iou_mean"]:
            a, b = min(span), max(span)
            inter = max(0.0, min(b, truth["t1"]) - max(a, truth["t0"]))
            union = max(b, truth["t1"]) - min(a, truth["t0"])
            best = {"cls": tr["cls"], "how": tr["how"], "seed_t": tr["seed_t"],
                    "iou_mean": round(m, 3), "iou_median": round(float(np.median(ious)), 3),
                    "frac_over_50": round(float(np.mean([i > 0.5 for i in ious])), 3),
                    "frac_over_75": round(float(np.mean([i > 0.75 for i in ious])), 3),
                    "tiou": round(inter / union if union > 0 else 0.0, 3), "samples": len(ious)}
    if best is not None:
        best["matched"] = best["frac_over_50"] > 0
    return best or {"iou_mean": 0.0, "tiou": 0.0, "samples": 0, "note": "inset never seeded"}


# ----------------------------------------------------------------------------- run

def run(clips: list[Path], prompts: list[str], out_dir: Path, seg: float = SEG,
        want_depth: bool = False) -> dict:
    from . import perceive as PC
    from . import tracking as TR
    from .sources import open_source

    out_dir.mkdir(parents=True, exist_ok=True)
    comp = out_dir / "clipeval.lua"
    truth = build(clips, comp, seg)
    print(f"clipeval: {len(clips)} clips, cuts at {truth['cuts']}", file=sys.stderr)
    src = open_source(comp)                      # renders through bin/cadence and caches
    media = src.media
    print(f"clipeval: rendered {media}", file=sys.stderr)

    t0 = time.time()
    text = PC.perceive(media, prompts, want_depth=want_depth,
                       log=lambda s: print(f"  % {s}", file=sys.stderr, flush=True))
    (out_dir / "clipeval.pl").write_text(text)
    facts = parse_log(text)
    got = [f[2] for f in facts if f[0] == "happens" and isinstance(f[1], tuple) and f[1][0] == "cut"]
    # The same bounds perceive used, so this is a cache hit rather than a second SAM pass. Scoring
    # against tracks built from the *truth* cuts would also flatter the result: the stack does not
    # get told where the cuts are, so the tracks it is judged on must be the ones it really made.
    tracks = TR.track(media, prompts, {}, src.duration,
                      bounds=[0.0] + sorted(got) + [src.duration], log=lambda s: None)

    res = {"clips": truth["sources"], "duration": truth["duration"], "secs": round(time.time() - t0, 1),
           "cuts": score_cuts(truth["cuts"], got), "inset": score_inset(truth["inset"], tracks),
           "facts": sum(1 for f in facts if f[0] in ("holds", "happens"))}
    (out_dir / "clipeval.json").write_text(json.dumps(res, indent=1))
    (out_dir / "report.md").write_text(report(res))
    return res


def report(r: dict) -> str:
    c, i = r["cuts"], r["inset"]
    L = ["# cadence-vision clip eval", "",
         f"{len(r['clips'])} source clips, {r['duration']:g}s assembled, {r['facts']} claims, {r['secs']}s", "",
         "## cut localization", "",
         f"truth {c['truth']} · found {c['found']} · matched {c['matched']} · "
         f"missed {c['missed']} · false positives {c['false_positives']}", "",
         "| off by | cuts |", "|---|---|"]
    L += [f"| {k} | {v}/{c['truth']} |" for k, v in c["within"].items()]
    L += ["", f"median {c['median_frames']} frames, worst {c['max_frames']} frames", "",
          "## inset localization", ""]
    if i.get("samples") and not i.get("matched", True):
        L += [f"**the inset was not matched.** The closest track, {i['how']} \"{i['cls']}\" seeded at "
              f"{i['seed_t']:.2f}s, reaches mean IoU {i['iou_mean']} and never once half-overlaps the "
              f"inset, so it is a different thing that happens to share the interval. No temporal IoU "
              f"is reported for it — that number would describe the wrong object."]
    elif i.get("samples"):
        L += [f"seeded by {i['how']} as \"{i['cls']}\" at {i['seed_t']:.2f}s, {i['samples']} samples", "",
              "| metric | value |", "|---|---|",
              f"| mean IoU | {i['iou_mean']} |", f"| median IoU | {i['iou_median']} |",
              f"| frames IoU > 0.5 | {i['frac_over_50']} |", f"| frames IoU > 0.75 | {i['frac_over_75']} |",
              f"| temporal IoU | {i['tiou']} |"]
    else:
        L.append("the inset was never seeded — recall 0, which is a seeder failure, not a scoring one")
    return "\n".join(L) + "\n"


def main(argv: list[str]) -> int:
    import argparse
    ap = argparse.ArgumentParser(prog="cadence-vision eval")
    ap.add_argument("--clips", required=True, help="directory of source clips, or a comma-separated list")
    ap.add_argument("--prompts", default="video panel,person,car",
                    help="concept prompts for the open-vocabulary seeder")
    ap.add_argument("--out", default=str(ROOT / "evals" / "out" / "clipeval"))
    ap.add_argument("--seg", type=float, default=SEG)
    ap.add_argument("--depth", action="store_true")
    a = ap.parse_args(argv)
    p = Path(a.clips)
    clips = sorted(q for q in p.iterdir() if q.suffix.lower() in {".mp4", ".mov", ".webm", ".mkv"}) \
        if p.is_dir() else [Path(x) for x in a.clips.split(",")]
    r = run(clips, a.prompts.split(","), Path(a.out), a.seg, a.depth)
    print(report(r))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
